### ISSUE TITLE
[Bug] Blank screen on the second login (Web/Android)

### ISSUE THREAD

**Issue by SemyonSinchenko** [Artawower/orgnote#13]
### Thank you for the bug report

- [X] I am using the latest version of the `OrgNote` app.
- [X] I already checked other related issues
- [X] I have read the [WIKI](https://github.com/Artawower/orgnote/wiki)

### Bug description and steps to reproduce

Reproducing:
- Log-in to orgnote (via GitHub SSO)
- Close the page (or app on Android) and browser
- Open browser and page
- See blank screen / app

### Debug info

Browser: Brave `Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) unknown (64-bit)`
Because I cannot load orgnote I cannot run debug too.

Strange errors I found in the Console:
```
Uncaught (in promise) SyntaxError (at index-BRgeT2BF.js:130:2265)
    at createCompileError (index-BRgeT2BF.js:130:2265)
    at createI18nError (index-BRgeT2BF.js:138:750)
    at useI18n (index-BRgeT2BF.js:138:16084)
    at useNotifications (index-BRgeT2BF.js:138:18919)
    at defineStore.persist (index-BRgeT2BF.js:178:4180)
    at EffectScope.run (index-BRgeT2BF.js:10:386)
    at index-BRgeT2BF.js:37:3755
    at EffectScope.run (index-BRgeT2BF.js:10:386)
    at index-BRgeT2BF.js:37:3728
    at runWithContext (index-BRgeT2BF.js:21:39475)
```
...
```
index-BRgeT2BF.js:192 Service worker is active.
index-BRgeT2BF.js:192 Service worker has been registered.
index-BRgeT2BF.js:130 Uncaught (in promise) SyntaxError (at index-BRgeT2BF.js:130:2265)
    at createCompileError (index-BRgeT2BF.js:130:2265)
    at createI18nError (index-BRgeT2BF.js:138:750)
    at useI18n (index-BRgeT2BF.js:138:16084)
    at useNotifications (index-BRgeT2BF.js:138:18919)
    at defineStore.persist (index-BRgeT2BF.js:178:4180)
    at EffectScope.run (index-BRgeT2BF.js:10:386)
    at index-BRgeT2BF.js:37:3755
    at EffectScope.run (index-BRgeT2BF.js:10:386)
    at index-BRgeT2BF.js:37:3728
    at runWithContext (index-BRgeT2BF.js:21:39475)
createCompileError @ index-BRgeT2BF.js:130
createI18nError @ index-BRgeT2BF.js:138
useI18n @ index-BRgeT2BF.js:138
useNotifications @ index-BRgeT2BF.js:138
defineStore.persist @ index-BRgeT2BF.js:178
run @ index-BRgeT2BF.js:10
(anonymous) @ index-BRgeT2BF.js:37
run @ index-BRgeT2BF.js:10
(anonymous) @ index-BRgeT2BF.js:37
runWithContext @ index-BRgeT2BF.js:21
createSetupStore @ index-BRgeT2BF.js:37
oO @ index-BRgeT2BF.js:37
(anonymous) @ index-BRgeT2BF.js:192
run @ index-BRgeT2BF.js:10
(anonymous) @ index-BRgeT2BF.js:37
run @ index-BRgeT2BF.js:10
(anonymous) @ index-BRgeT2BF.js:37
runWithContext @ index-BRgeT2BF.js:21
createSetupStore @ index-BRgeT2BF.js:37
oO @ index-BRgeT2BF.js:37
cO @ index-BRgeT2BF.js:192
(anonymous) @ index-BRgeT2BF.js:192
callWithErrorHandling @ index-BRgeT2BF.js:21
callWithAsyncErrorHandling @ index-BRgeT2BF.js:21
PO @ index-BRgeT2BF.js:21
flushPreFlushCbs @ index-BRgeT2BF.js:21
GO @ index-BRgeT2BF.js:21
mount @ index-BRgeT2BF.js:21
tO.mount @ index-BRgeT2BF.js:29
start @ index-BRgeT2BF.js:192
await in start
(anonymous) @ index-BRgeT2BF.js:192
Promise.then
(anonymous) @ index-BRgeT2BF.js:192
Promise.then
(anonymous) @ index-BRgeT2BF.js:192
index-BRgeT2BF.js:139 QPage needs to be child of QPageContainer
console.<computed> @ index-BRgeT2BF.js:139
setup @ QPage-DUBZyIAE.js:1
callWithErrorHandling @ index-BRgeT2BF.js:21
setupStatefulComponent @ index-BRgeT2BF.js:21
setupComponent @ index-BRgeT2BF.js:21
ZO @ index-BRgeT2BF.js:21
RO @ index-BRgeT2BF.js:21
gO @ index-BRgeT2BF.js:21
n$ @ index-BRgeT2BF.js:21
run @ index-BRgeT2BF.js:10
XO.update @ index-BRgeT2BF.js:21
kh @ index-BRgeT2BF.js:21
ZO @ index-BRgeT2BF.js:21
RO @ index-BRgeT2BF.js:21
gO @ index-BRgeT2BF.js:21
pO @ index-BRgeT2BF.js:21
CO @ index-BRgeT2BF.js:21
EO @ index-BRgeT2BF.js:21
gO @ index-BRgeT2BF.js:21
n$ @ index-BRgeT2BF.js:21
run @ index-BRgeT2BF.js:10
XO.update @ index-BRgeT2BF.js:21
kh @ index-BRgeT2BF.js:21
ZO @ index-BRgeT2BF.js:21
RO @ index-BRgeT2BF.js:21
gO @ index-BRgeT2BF.js:21
n$ @ index-BRgeT2BF.js:21
run @ index-BRgeT2BF.js:10
XO.update @ index-BRgeT2BF.js:21
kh @ index-BRgeT2BF.js:21
ZO @ index-BRgeT2BF.js:21
RO @ index-BRgeT2BF.js:21
gO @ index-BRgeT2BF.js:21
n$ @ index-BRgeT2BF.js:21
run @ index-BRgeT2BF.js:10
XO.update @ index-BRgeT2BF.js:21
callWithErrorHandling @ index-BRgeT2BF.js:21
flushJobs @ index-BRgeT2BF.js:21
Promise.then
queueFlush @ index-BRgeT2BF.js:21
queuePostFlushCb @ index-BRgeT2BF.js:21
queueEffectWithSuspense @ index-BRgeT2BF.js:21
kO @ index-BRgeT2BF.js:21
resetScheduling @ index-BRgeT2BF.js:10
triggerEffects @ index-BRgeT2BF.js:10
triggerRefValue @ index-BRgeT2BF.js:10
set value @ index-BRgeT2BF.js:10
yO @ index-BRgeT2BF.js:33
(anonymous) @ index-BRgeT2BF.js:33
Promise.then
WO @ index-BRgeT2BF.js:33
QO @ index-BRgeT2BF.js:33
install @ index-BRgeT2BF.js:33
use @ index-BRgeT2BF.js:21
start @ index-BRgeT2BF.js:192
await in start
(anonymous) @ index-BRgeT2BF.js:192
Promise.then
(anonymous) @ index-BRgeT2BF.js:192
Promise.then
(anonymous) @ index-BRgeT2BF.js:192
index-BRgeT2BF.js:139 TypeError: n.loadActiveExtensions is not a function
    at MainLayout-CDYltXpG.js:29:9935
    at index-BRgeT2BF.js:21:28499
    at callWithErrorHandling (index-BRgeT2BF.js:21:866)
    at callWithAsyncErrorHandling (index-BRgeT2BF.js:21:1004)
    at tO.__weh.tO.__weh (index-BRgeT2BF.js:21:28279)
    at invokeArrayFns$1 (index-BRgeT2BF.js:14:1774)
    at ReactiveEffect.n$ [as fn] (index-BRgeT2BF.js:21:56527)
    at ReactiveEffect.run (index-BRgeT2BF.js:10:1938)
    at XO.update (index-BRgeT2BF.js:21:57249)
    at kh (index-BRgeT2BF.js:21:57290)
console.<computed> @ index-BRgeT2BF.js:139
logError$1 @ index-BRgeT2BF.js:21
handleError$1 @ index-BRgeT2BF.js:21
(anonymous) @ index-BRgeT2BF.js:21
Promise.catch
callWithAsyncErrorHandling @ index-BRgeT2BF.js:21
tO.__weh.tO.__weh @ index-BRgeT2BF.js:21
invokeArrayFns$1 @ index-BRgeT2BF.js:14
n$ @ index-BRgeT2BF.js:21
run @ index-BRgeT2BF.js:10
XO.update @ index-BRgeT2BF.js:21
kh @ index-BRgeT2BF.js:21
ZO @ index-BRgeT2BF.js:21
RO @ index-BRgeT2BF.js:21
gO @ index-BRgeT2BF.js:21
n$ @ index-BRgeT2BF.js:21
run @ index-BRgeT2BF.js:10
XO.update @ index-BRgeT2BF.js:21
callWithErrorHandling @ index-BRgeT2BF.js:21
flushJobs @ index-BRgeT2BF.js:21
Promise.then
queueFlush @ index-BRgeT2BF.js:21
queuePostFlushCb @ index-BRgeT2BF.js:21
queueEffectWithSuspense @ index-BRgeT2BF.js:21
kO @ index-BRgeT2BF.js:21
resetScheduling @ index-BRgeT2BF.js:10
triggerEffects @ index-BRgeT2BF.js:10
triggerRefValue @ index-BRgeT2BF.js:10
set value @ index-BRgeT2BF.js:10
yO @ index-BRgeT2BF.js:33
(anonymous) @ index-BRgeT2BF.js:33
Promise.then
WO @ index-BRgeT2BF.js:33
QO @ index-BRgeT2BF.js:33
install @ index-BRgeT2BF.js:33
use @ index-BRgeT2BF.js:21
start @ index-BRgeT2BF.js:192
await in start
(anonymous) @ index-BRgeT2BF.js:192
Promise.then
(anonymous) @ index-BRgeT2BF.js:192
Promise.then
(anonymous) @ index-BRgeT2BF.js:192
```
...
```
TypeError: n.loadActiveExtensions is not a function
    at MainLayout-CDYltXpG.js:29:9935
    at index-BRgeT2BF.js:21:28499
    at callWithErrorHandling (index-BRgeT2BF.js:21:866)
    at callWithAsyncErrorHandling (index-BRgeT2BF.js:21:1004)
    at tO.__weh.tO.__weh (index-BRgeT2BF.js:21:28279)
    at invokeArrayFns$1 (index-BRgeT2BF.js:14:1774)
    at ReactiveEffect.n$ [as fn] (index-BRgeT2BF.js:21:56527)
    at ReactiveEffect.run (index-BRgeT2BF.js:10:1938)
    at XO.update (index-BRgeT2BF.js:21:57249)
    at kh (index-BRgeT2BF.js:21:57290)
```

### Additional context

If I delete all the page data (or delete all the data from the app) I can successfully log in back and see my notes. But if I close the page (app) the problem appears again.

**Comment by Artawower** [comment]
I'm not sure of the real reason, but one of the possible bugs was fixed in the latest release, could you check the latest version? (0.21.3)

**Comment by SemyonSinchenko** [comment]
With 0.21.3 the problem disappears! Thank you!
