### ISSUE TITLE
[Bug] Org file fails to open/does not get indexed.

### ISSUE THREAD

**Issue by schilkp** [Artawower/orgnote#31]
### Thank you for the bug report

- [X] I am using the latest version of the `OrgNote` app.
- [X] I already checked other related issues
- [X] I have read the [WIKI](https://github.com/Artawower/orgnote/wiki)

### Bug description and steps to reproduce

The following org file fails to open in OrgNote on android, and also does not get indexed.

```org
:PROPERTIES:
:ID:       c7e56e3d-73b2-40fa-b890-b617ac2caf2f
:END:
#+title: Fundamental Theorem of Algebra

* Statement

Every (univariant) polynomial of the form:


$$ p(z) := z^n + a_{n-1}z^{n-a} + \ldots + a_1 z + a_0 $$

with complex coefficients $a_k$ of order $n \geq 1$ has at least one
root (is at least equal to 0 at one) $z_0 \in \mathbb{C}$.

Also "d'Alembert's theorem".

* Consequences

- Such polynomials can be factorized as $c (x-r_1) \cdots (x-r_n)$,
  where $c, r_n$ are all complex numbers. Follows by recursion:

  Let $r_1$ be the root of one such polynomial

  Divide by $(x-r_1)$ yielding a polynomial of order $n-1$

  This, by the original theorem, has at least one complex root $r_2$,
  and so forth.

- For such polynomials **with real coefficients**, if $r$ is a
  *non-real* root, then $\bar{r}$ is also a root.

- Such polynomials **with real coefficients** and order $n >2$, by the
  [[id:45cb1c16-6d34-462f-8ebe-b01b4c79bd22][Complex Conjugate Root Theorem]], have at least one factor of degree
  two with real coefficients.

- Such polynomials **with real coefficients** have:
   - $r$ real root $\alpha_1, \alpha_2, ..., \alpha_r$ with respective
     algebraic multiplicity $l_1, l_2, \ldots, l_r$

   - $s$ pairs $\zeta_k = \beta_k + i\gamma_k, \; \;\bar{\zeta} = \beta_k - i \gamma_k \; \; (1 \leq k \leq s)$
     of complex roots with respective algebraic multiplicity $m_k$.

   - Of course: $l_1 + \ldots + l_r + 2m_1 + ... + 2m_s = n$

   - And can be written as:

     $(x-\alpha_1)^{l_1} \cdots (x-\alpha_r)^{l_r} (Q_1(x))^{m_1} \cdots (Q_s(x))^{m_s}$

     With:

     $Q_k(x) := (x - \zeta_k)(x-\bar{\zeta}_k) = (x-\beta_k)^2 + \gamma_k^2 = x^2 + b_k x + c_k$

* References
  - [[id:d03d4665-0634-4a7f-82cd-df748c7d423a][@Ingenieur Analysis 1]]
```

I tried to binary-search which lines causes the issue, and it seems to be something in the last 5-10 lines - but I could not precisely track it down.

Attempting to open to file from the left file sidebar, generates the following error:

```
[error] ["QPage needs to be child of QPageContainer"] 
[warn] [{}] (5)
[error] "[line: undefined, col: undefined] mes: \"Converting circular structure to JSON\\n    --> starting at object with constructor 'OrgNode'\\n    |     property 'parent' -> object with constructor 'OrgNode'\\n    |     property 'children' -> object with constructor 'OrgChildrenList'\\n    |     property 'header' -> object with constructor 'OrgListChild'\\n    --- property 'value' closes the circle\"\n\tTypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'OrgNode'\n    |     property 'parent' -> object with constructor 'OrgNode'\n    |     property 'children' -> object with constructor 'OrgChildrenList'\n    |     property 'header' -> object with constructor 'OrgListChild'\n    --- property 'value' closes the circle\n    at JSON.stringify (<anonymous>)\n    at https://localhost/assets/index-CZ7rGJWS.js:134:351\n    at Array.map (<anonymous>)\n    at oO (https://localhost/assets/index-CZ7rGJWS.js:134:338)\n    at https://localhost/assets/index-CZ7rGJWS.js:134:60" 
[warn] [{}] (1)
```

### Debug info

```
OrgNote: 0.22.7
Language: en-US

Screen:
  Screen resolution: 427x952
  Screen color depth: 24
  Device pixel ratio: 2.25

Encryption:
  Type: disabled

Env:
  API URL: https://org-note.com/api/v1/
  AUTH URL: https://org-note.com
  MODE: production

Quasar info:
  chrome: true
  version: 131.0.6778.200
  versionNumber: 131
  android: true
  mobile: true
  webkit: true
  name: chrome
  platform: android
  capacitor: true
  nativeMobile: true
  nativeMobileWrapper: capacitor
 standalone: false

Device info:
  Model: Pixel 9 Pro
  Manufacturer: Google
  SDK version: 35
  Version: 15
```

### Additional context

Thanks for the great app!

**Comment by Artawower** [comment]
Thanks for the bug report. Can you please check the latest release from [github releases page](https://github.com/Artawower/orgnote-client/releases)?

**Comment by schilkp** [comment]
Seems to be working. Thanks!
